export const GET_JOBS_BEGIN = 'GET_JOBS_BEGIN'
export const GET_JOBS_SUCCESS = 'GET_JOBS_SUCCESS'

export const  PRICE_ORDER_BEGIN = 'PRICE_ORDER_BEGIN'
export const  PRICE_ORDER_SUCCESS = 'PRICE_ORDER_SUCCESS'

export const  ASCENDING_PRICE_TRUE = 'ASCENDING_PRICE_TRUE'
export const  ASCENDING_PRICE_FALSE = 'ASCENDING_PRICE_FALSE'